// FAKE DATA
export const books = [
  {
    id: 1,
    title: "Coding All-In-One For Dummies",
    url: "https://m.media-amazon.com/images/I/71xdJ65b4RL._SL1500_.jpg",
    originalPrice: 41.99,
    salePrice: 24.72,
    rating: 4.5,
  },
  {
    id: 2,
    title: "Outlive: The Science and Art of Longevity",
    url: "https://m.media-amazon.com/images/I/71exiwQ24oL._SL1500_.jpg",
    originalPrice: 32.00,
    salePrice: 15.28,
    rating: 4.6,
  },
  {
    id: 3,
    title: "Science of Stretch",
    url: "https://m.media-amazon.com/images/I/81Ynx92-NFL._SL1500_.jpg",
    originalPrice: 24.99,
    salePrice: 15.31,
    rating: 4.8,
  },
  {
    id: 4,
    title: "Berserk Dexluxe Volume 1",
    url: "https://m.media-amazon.com/images/I/91eRoWSACCL._SL1500_.jpg",
    originalPrice: 49.99,
    salePrice: 29.95,
    rating: 4.9,
  },
  {
    id: 5,
    title: "Jujutsu Kaisen, Vol. 1",
    url: "https://m.media-amazon.com/images/I/81TmHlRleJL._SL1500_.jpg",
    originalPrice: 11.99,
    salePrice: 9.59,
    rating: 4.8,
  },
  {
    id: 6,
    title: "One Piece, Vol. 1: Romance Dawn ",
    url: "https://m.media-amazon.com/images/I/91NxYvUNf6L._SL1500_.jpg",
    originalPrice: 11.99,
    salePrice: 6.73,
    rating: 4.8,
  },
  {
    id: 7,
    title: "Uzumaki",
    url: "https://m.media-amazon.com/images/I/81CfbcFFyHL._SL1500_.jpg",
    originalPrice: 35.00,
    salePrice: 19.99,
    rating: 4.9,
  },
  {
    id: 8,
    title: "One-Punch Man, Vol. 1",
    url: "https://m.media-amazon.com/images/I/81VAgJoB3BL._SL1500_.jpg",
    originalPrice: 11.99,
    salePrice: 7.79,
    rating: 4.8,
  },
  {
    id: 9,
    title: "Don't Believe Everything You Think",
    url: "https://m.media-amazon.com/images/I/91F9s5PtXVL._SL1500_.jpg",
    originalPrice: 22.00,
    salePrice: 12.54,
    rating: 4.6,
  },
  {
    id: 10,
    title: "The Psychology of Money",
    url: "https://m.media-amazon.com/images/I/81gC3mdNi5L._SL1500_.jpg",
    originalPrice: 19.99,
    salePrice: 10.99,
    rating: 4.7,
  },
  {
    id: 11,
    title: "Thinking, Fast and Slow",
    url: "https://m.media-amazon.com/images/I/61fdrEuPJwL._SL1500_.jpg",
    originalPrice: 22.00,
    salePrice: 11.83,
    rating: 4.6,
  },
  {
    id: 12,
    title: "The Body Keeps the Score",
    url: "https://m.media-amazon.com/images/I/71Ha3OShqSL._SL1500_.jpg",
    originalPrice: 19.99,
    salePrice: 14.24,
    rating: 4.8,
  },
];